// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Swarmwright.Database;

#nullable disable

namespace Swarmwright.Database.Sqlite.Migrations
{
    [DbContext(typeof(SwarmDbContext))]
    [Migration("20260607151438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Swarmwright.Database.Models.AgentEntity", b =>
                {
                    b.Property<Guid>("SwarmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("swarm_id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TasksCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tasks_completed");

                    b.HasKey("SwarmId", "Name");

                    b.HasIndex("SwarmId")
                        .HasDatabaseName("idx_agents_swarm_id");

                    b.ToTable("swarm_agents");
                });

            modelBuilder.Entity("Swarmwright.Database.Models.EventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("SwarmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("swarm_id");

                    b.HasKey("Id");

                    b.HasIndex("SwarmId", "CreatedAt")
                        .HasDatabaseName("idx_events_swarm_created");

                    b.HasIndex("SwarmId", "EventType")
                        .HasDatabaseName("idx_events_swarm_type");

                    b.ToTable("swarm_events");
                });

            modelBuilder.Entity("Swarmwright.Database.Models.FileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("SwarmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("swarm_id");

                    b.HasKey("Id");

                    b.HasIndex("SwarmId", "Path")
                        .IsUnique()
                        .HasDatabaseName("idx_files_swarm_path");

                    b.ToTable("swarm_files");
                });

            modelBuilder.Entity("Swarmwright.Database.Models.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sender");

                    b.Property<Guid>("SwarmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("swarm_id");

                    b.HasKey("Id");

                    b.HasIndex("SwarmId", "CreatedAt")
                        .HasDatabaseName("idx_messages_swarm_created");

                    b.ToTable("swarm_messages");
                });

            modelBuilder.Entity("Swarmwright.Database.Models.SwarmEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AutoSmartContinueCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_smart_continue_count");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("context_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_round");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("goal");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_by");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_rounds");

                    b.Property<string>("QaRefinedGoal")
                        .HasColumnType("TEXT")
                        .HasColumnName("qa_refined_goal");

                    b.Property<string>("Report")
                        .HasColumnType("TEXT")
                        .HasColumnName("report");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("SynthesisSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("synthesis_session_id");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("template_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("swarms");
                });

            modelBuilder.Entity("Swarmwright.Database.Models.SwarmStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_state");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<Guid>("SwarmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("swarm_id");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("to_state");

                    b.HasKey("Id");

                    b.HasIndex("SwarmId", "CreatedAt")
                        .HasDatabaseName("idx_swarm_transitions_swarm_created");

                    b.ToTable("swarm_state_transitions");
                });

            modelBuilder.Entity("Swarmwright.Database.Models.TaskEntity", b =>
                {
                    b.Property<Guid>("SwarmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("swarm_id");

                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BlockedByJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("blocked_by_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_name");

                    b.Property<string>("WorkerRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_role");

                    b.HasKey("SwarmId", "Id");

                    b.HasIndex("SwarmId")
                        .HasDatabaseName("idx_tasks_swarm_id");

                    b.ToTable("swarm_tasks");
                });

            modelBuilder.Entity("Swarmwright.Database.Models.TaskStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_state");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<int>("RetryCountAfter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count_after");

                    b.Property<Guid>("SwarmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("swarm_id");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("to_state");

                    b.HasKey("Id");

                    b.HasIndex("SwarmId", "TaskId", "CreatedAt")
                        .HasDatabaseName("idx_task_transitions_task_created");

                    b.ToTable("task_state_transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
